### PR TITLE
Add AES, Performance boosts, Comments and More!

### PR DESCRIPTION
**Pull request by TotallyNotChase**
There's too many changes to mention here so here's a full [Changelog!](https://gist.github.com/TotallyNotChase/bb54f874b66f264f3bcdfe663579a214)

### CODE REVIEW

**Comment by TotallyNotChase** [comment]
Here's hoping I didn't make too many dumb mistakes

**Comment by TotallyNotChase** [comment]
This should close #3

**Comment by M4cs** [comment]
Before i test and out and merge this i notice you didn't add new deps to the `pyproject.toml` for poetry. I don't have contribution guidelines so that's my bad but if you could just add PyCrypto as a dep with the version needed to the file that would help a bunch!

**Comment by M4cs** [comment]
Just tested this out and it seems to be working w/ a few changes to the test that I will add once this is merged!

**Comment by M4cs** [comment]
Gonna go ahead and merge this, don't worry about the dep, ill fix that

**Comment by TotallyNotChase** [comment]
Oops, I reminded myself to add the dependencies but then ultimately forgot. Sorry for that. I am off to sleep for now because timezones suck so thanks for adding it!

**Pull request merged**
